services:
  app:
    build:
      context: app

    container_name: app

    image: app

    restart: always

    volumes:
      - logs:/var/log/gunicorn

    ports:
      - "8080:8080"

    networks:
      webnet:
        aliases:
          - app

  nginx:
    container_name: nginx

    image: nginx

    ports:
      - 80:80
      - 443:443

    depends_on:
      - app

    restart: always

    networks:
      webnet:
        aliases:
          - nginx

    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro

  certbot:
    image: certbot/certbot:latest
    volumes: 
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrpt/:rw

networks:
  webnet:

volumes:
  logs: