services:
  app:
    build:
      context: app

    container_name: app

    image: app

    restart: always

    volumes:
      - logs:/var/log/gunicorn

    ports:
      - "8080:8080"

volumes:
  logs: